### ISSUE TITLE
why

### ISSUE THREAD

**Issue by miclgael** [bclindner/emojo.site#1]
😿

**Comment by fakefred** [comment]
![:cate:](https://cdn.mastodon.technology/custom_emojis/images/000/074/675/original/71593e05a95bd8a7.png)

**Comment by bclindner** [comment]
Thanks for your issue submission!

Unfortunately, resolving this issue is beyond the scope of the initial release, and we don't intend to add this to our scope moving forward. Apologies!

**Comment by crutchcorn** [comment]
i must inform you - is good

p.s. bra-vo on owning https://badat.dev - you've spoiled my plans to utilize it to make fun of myself :(
